{
    'name': "CRM Étudiants",
    'summary': "Gestion des étudiants avec CRM",
    'description': "Module de gestion des étudiants avec fonctionnalités CRM",
    'author': "Basilio, Luca, Manantsoa IGF-IA/PRO42",
    'category': 'Education',
    'version': '18.0.1.0.0',
    'depends': ['base', 'crm', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/etudiant_views.xml',
        'views/etudiant_menu.xml',
        'views/stage_views.xml',
        'views/crm_views.xml',
        'views/crm_lead_kanban_views.xml',
        'views/crm_list_views.xml',
        'views/contact_views.xml',
        'views/professeur_menu.xml',
        'views/professeur_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}